import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { myCustomFont } from './ui/fonts';
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${myCustomFont.className} min-h-screen flex flex-col`} >
      <body className="flex flex-col min-h-screen flex-grow">
        <Navbar />

        <main className="flex-grow">
      {children}
    </main>
        <Footer />
      </body>
    </html>
  );
}
